### ISSUE TITLE
Feedback for “What is Lama Cleaner”

### ISSUE THREAD

**Issue by andrewkireev** [Sanster/lama-cleaner-docs#22]
Hi! I bought a one-click installer for windows but I see this when I try to run the script. What is the problem?
I working under windows 11

<img width="684" alt="Screenshot 2023-04-20 232442" src="https://user-images.githubusercontent.com/51882696/233449359-33223424-2af8-4e0d-8b0a-9ce2923ccb6d.png">

**Comment by Sanster** [comment]
Hi, did you move the directory after unzipping the zip package?

**Comment by andrewkireev** [comment]
Yes, I did. Thank you, I was able to run it.
